version: '3.8'  # Możesz użyć odpowiedniej wersji

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteka