managment:
  endpoints:
    exposure:
      include: '*'

  info:
    env:
      enabled: true
  application:
    name: spring-bibliotekaApp
    description: Aplikacja do działania na bazie danych Biblioteka.
    author: Kamil Dorszewski
    version: '0.0.1-SNAPSHOT'
  spring:
    profiles:
      active: dev